### ISSUE TITLE
ngcart-addtocart data attribute is unusable with custom value

### ISSUE THREAD

**Issue by humbkr** [snapjay/ngCart#10]
When I try to display any variable from my controller, for example:
`<ngcart-addtocart id="{{item.id}}"
                          name="{{item.label}}"
                          price="{{item.price}}"
                          quantity="1"
                          data="{{item.label}}">Add to cart</ngcart-addtocart>
`

I get an angular error:
Error: [$parse:syntax] Syntax Error: Token '{' invalid key at column 2 of the expression [{{item.label}}] starting at [{item.label}}].

I suppose that the attribute "data" must be special to angular somehow, because it works with any other attribute name.

**Comment by seopolis** [comment]
In the code you are giving you are not trying to display something, but to add a new product to the cart. If you provide a codepen or jsfiddle I could help you, because I display this value without any issues.

**Comment by humbkr** [comment]
I updated the issue to display the right code.

**Comment by snapjay** [comment]
The data attribute is 2-way binding - this means you should not place your $scope value in the {{ brackets.
Try data="myVariable" and it should work

**Comment by humbkr** [comment]
Indeed, it works better that way. Thanks!

**Comment by wayko** [comment]
I got it to work 
    <ngcart-addtocart id="{{all.id}}" name="{{all.name}}" price="{{all.price}}" quantity="1" quantity-max="{{all.available}}"><img src="images/shoppingbag.png" class="box cartItem"></ngcart-addtocart>  

just had to make sure the keys matched what it was looking for when I did all.price I used  " | currency " on ngcart-addtocart but it was already filtering this in his code
