### ISSUE TITLE
add isInCart(item) method to ngCart

### ISSUE THREAD

**Issue by programming-kid** [snapjay/ngCart#14]
hey this is life saver plug-in thanks for authoring this 

this is nothing but a small request can you pls add ```isInCart(itemId)``` method to ngCart to check if item is in cart or not

this would be really helpful if its in-built instead implementing it manually everytime

thanks

**Comment by snapjay** [comment]
You can use ngCart.getItemById(id) and check if you get false.  
Not sure there is a need for an additional method here to essential to the same thing.
