### ISSUE TITLE
Your Github tags don't mach your bower version

### ISSUE THREAD

**Issue by FranzZemen** [snapjay/ngCart#15]
Not sure if this is intentional, but it limits ability to pull newest declared bower version.

bower.json version:  0.0.3-rc.1

lastest version reported by bower: 0.0.2-rc.1.0

**Comment by snapjay** [comment]
0.0.3-rc.1 is the current version in the master branch which has not been released yet.
The 0.0.2-rc.1.0 version in the current release.
