### ISSUE TITLE
Clear cart

### ISSUE THREAD

**Issue by zekone** [snapjay/ngCart#17]
Consider the addition of a ngCart.clear() to empty all contents of a cart. Could be called when a user logs out.

**Comment by snapjay** [comment]
This already exists; try calling ngCart.empty()

**Comment by 1110815AdamSilva** [comment]
I suggest you alter the documentation to make it clear please. I understood that that function would return a boolean like true if the cart was empty and false if it wasn't. It doesn't say anything about clearing the whole cart.

**Comment by lupetalo** [comment]
Yep, doc is not clear, I was also trying to get empty status with this function...
