### ISSUE TITLE
Sending custom data to checkout

### ISSUE THREAD

**Issue by punkshui** [snapjay/ngCart#24]
Hello, thanks for your excellent library here. I'm using it in a project where I have to send customer details along with the products in the cart to a public api. For this purpose, when the user clicks on checkout in the cart view they get a form where they have to enter certain fields necessary for shipping purposes. Is there a way to append this form data to the POST request sent from the checkout button within your library or will this require some customisation on my part?

**Comment by amejiarosario** [comment]
@punkshui did you find a way to do it?

**Comment by punkshui** [comment]
@amejiarosario Since I'm making a request to my API in addition to sending the cart to paypal I've had to make an API request to paypal and wasn't able to use ngCart. It would have been possible to extend the paypal service directive to do this, but I don't like to touch package source code.
