### ISSUE TITLE
ngCart - All Directives Render entirely new page and no button

### ISSUE THREAD

**Issue by leonbold87** [snapjay/ngCart#39]
We're trying to use ngCart in our online store, but every directive we use just renders the index.html and nothing else. 
<img width="775" alt="screen shot 2015-09-05 at 7 38 23 pm" src="https://cloud.githubusercontent.com/assets/5638801/9701717/b9b9d44a-5405-11e5-91a4-b55fb7a9f7c1.png">

**Comment by snapjay** [comment]
This is most likely because you are getting a 404 on your templates.  Please make sure they are in the right location
