### ISSUE TITLE
How to change the price of the unit (eg:$ 100.00  to￥100.00）

### ISSUE THREAD

**Issue by ittray** [snapjay/ngCart#44]
How to change the price of the unit (eg:$ 100.00  to￥100.00）

**Comment by ittray** [comment]
angularjs:
CURRENCY_SYM:"$" to CURRENCY_SYM:"￥"

**Comment by snapjay** [comment]
ngCart uses the currency filter.
You can update your templates or use the  $locale service.
https://docs.angularjs.org/guide/i18n
