### ISSUE TITLE
Paypal settings not being passed into form input values

### ISSUE THREAD

**Issue by lukashambsch** [snapjay/ngCart#45]
The paypal checkout button isn't working correctly for me. After looking into it, I realized the values passed in settings are not being bound to the input values in the form. The business input is being bound to settings.paypal.business. When I format the settings object with paypal as the first key it works correctly. For example: `{"paypal": {"business": "blah@gmail.com"}}` works correctly. Should the service attribute of the input ngcart-checkout element be automatically specified as the first key?

**Comment by stcalica** [comment]
`<input type="hidden" name="business" value="{{ settings.paypal.business }}" />`

in the controller where the checkout button is it seems like you should have: 

`$scope.settings  =  {"paypal": {"business": "blah@gmail.com"}}`

wouldn't that equate to 

`settings.paypal.business` in the view?
