### ISSUE TITLE
How to get each item's id in controller???

### ISSUE THREAD

**Issue by SharkIng** [snapjay/ngCart#56]
I am going to need send my data (cart and user info) to my backend. But i try to use for (item in ngCart.getCart()) to get each item's id buut it does not work. anyoen have idea how to do it?

**Comment by SharkIng** [comment]
OK, I think i solve that problem. 

But i have one new question. Is there any function to empty cart?? Like if user want to empty all items or after checkout to refrush cart

**Comment by snapjay** [comment]
See the documentation http://ngcart.snapjay.com/docs
ngCart.empty() will empty the cart.
Please keep this space for issues; not help with implementation.
