### ISSUE TITLE
Allow custom templates path (404 errors on templates files)

### ISSUE THREAD

**Issue by humbkr** [snapjay/ngCart#6]
After installing you library via Bower, the js requests templates in "<APP_ROOT>/template/ngCart", wich gives 404 errors since the files are located in "<APP_ROOT>bower_components/ngCart/template/ngCart".

I can obviously redefine the templates files, but even if I do that I'm stuck with the relative path you chose, ie "/template/ngCart", whereas my app's templates are located in a different folder.

It would be great to be able to specify where are located the templates you want to use.

**Comment by snapjay** [comment]
This is the intended behavior.
The templates files should be copied to your app/template so you can customize them to your site.
This is following the AngularJS standard practice - For an other example see 
http://angular-ui.github.io/bootstrap/


I do not believe current version of AngularJS lets you have dynamic template locations.

**Comment by humbkr** [comment]
I'm new to angular but it bothers me that a component imposes me my app's structure.
I generated my app structure using yeoman, which creates an app/views directory, where the templates should be located.

What if I want to split my app's functionnalities into modules, with for example a module "ecommerce" that would contains all the templates / controllers / directives needed for this part of  the app?

A good example here: https://scotch.io/tutorials/angularjs-best-practices-directory-structure

Is app/template the standard angular folder to store templates for external components?

**Comment by brutalhonesty** [comment]
@humbkr :+1:

**Comment by brutalhonesty** [comment]
@humbkr As a work-around, I've added the templates files wrapped in script files as seen below:

```html
<script type="text/ng-template" id="template/ngCart/summary.html">
  <!-- MY HTML HERE -->
</script>
<script type="text/ng-template" id="template/ngCart/cart.html">
  <!-- MY HTML HERE -->
</script>
<script type="text/ng-template" id="template/ngCart/addtocart.html">
  <!-- MY HTML HERE -->
</script>
```

I stored this file in client/app/path/to/file.tpl.html and then in my index.html file I ng-included them as seen below:

```html
<body>
  <!-- Some other stuff here -->
  <div ng-include="'app/path/to/file.tpl.html'"></div>
</body>
```

With that, the templates were found by ngCart and the cart loaded.

**Comment by brutalhonesty** [comment]
Alternatively, if you are having issues with the this, you can add a route in your Express app (or whichever your server is) to point to route to the proper location.

Example would be if you keep your template files in client/components/ngCart/ then the added Express code is:

```js
app.use('/template', express.static(path.join(config.root, 'client/components')));
```

With this, express loads the route properly.

**Comment by humbkr** [comment]
Thanks for the tips @brutalhonesty !

**Comment by brutalhonesty** [comment]
It seems that there are going to still be issues if you use $templateCache in your task runners for production code. Using ngtemplates for Grunt, the files are cached in the following manner:
```javascript
// app.js
$templateCache.put("components/ngCart/addtocart.html", '<div ng-hide=attrs.id><a class="btn btn-lg btn-primary" ng-disabled=true ng-transclude></a></div><div ng-show=attrs.id><div ng-hide=inCart()><a class="btn btn-lg btn-primary" ng-click="ngCart.addItem(id, name, price, quantity, data)" ng-transclude></a></div><div class="alert alert-info" ng-show=inCart()>This item is in your cart</div></div>');
$templateCache.put("components/ngCart/cart.html", '<div class="alert alert-warning" role=alert ng-show="ngCart.totalItems() === 0">Your cart is empty</div><div class="table-responsive col-lg-12" ng-show="ngCart.totalItems() > 0"><table class="table table-striped ngCart cart"><thead><tr><th></th><th></th><th>Quantity</th><th>Amount</th><th>Total</th></tr></thead><tfoot><tr ng-show=ngCart.getTax()><th></th><th></th><th></th><th>Tax ({{ ngCart.getCart().tax }}%):</th><th>{{ ngCart.getTax() | currency }}</th></tr><tr ng-show=ngCart.getShipping()><th></th><th></th><th></th><th>Shipping:</th><th>{{ ngCart.getShipping() | currency }}</th></tr><tr><th></th><th></th><th></th><th>Total:</th><th>{{ ngCart.totalCost() | currency }}</th></tr></tfoot><tbody><tr ng-repeat="item in ngCart.getCart().items track by $index"><td><span ng-click=ngCart.removeItem($index) class="fa fa-times"></span></td><td>{{ item.getName() }}</td><td><span class="fa fa-minus" ng-class="{\'disabled\':item.getQuantity()==1}" ng-click="item.setQuantity(-1, true)"></span>&nbsp;&nbsp; {{ item.getQuantity() | number }}&nbsp;&nbsp; <span class="fa fa-plus" ng-click="item.setQuantity(1, true)"></span></td><td>{{ item.getPrice() | currency}}</td><td>{{ item.getTotal() | currency }}</td></tr></tbody></table></div><style>.ngCart.cart span[ng-click] {\n' + "        cursor: pointer;\n" + "    }\n" + "    .ngCart.cart .glyphicon.disabled {\n" + "        color:#aaa;\n" + "    }</style>");
$templateCache.put("components/ngCart/summary.html", "<div class=grid><div class=col-1-3><i class=\"fa fa-shopping-cart\"></i></div><div class=col-2-3>{{ ngCart.totalItems() }}<ng-pluralize count=ngCart.totalItems() when=\"{1: 'item', 'other':'items'}\"></ng-pluralize>{{ ngCart.totalCost() | currency }}</div></div>");
```

With this, express cannot route /template/* to a file as the files are in the Angular $templateCache. I'm still trying to figure out how I can direct the request from express to Angular with the proper route.

**Comment by atomworks** [comment]
Stumbled on this and thought I'd have to get creative too but it seems since this discussion the functionality has been added.

Use this attribute on the relevant directives: template-url="/custom/url.html"

**Comment by snapjay** [comment]
Interesting; do you have a jsFiddle?

**Comment by atomworks** [comment]
I don't. Is there a quick template you know of for one I can work off? I'm a little stretched for time though I'd like to put together an example though the sticking point on time is that I'm a little unfamiliar actually putting something together from scratch on jsFiddle.

You say "interesting". Did you not actually implement this? I double checked and I'm using your repo!

**Comment by wallyhall** [comment]
I'm no expert in AngularJS, I've been fighting this exact issue with a programming buddy all afternoon.

Eventually we tripped across [another question on SO][1] which describes a vastly more elegant solution.

(I've also commented on the GitHub issue tracking page, for future reference.)

In short:

    <ngcart-summary template-url="/libraries/ngCart/template/ngCart/summary.html"></ngcart-summary>

  [1]: http://stackoverflow.com/questions/38690105/template-not-found-using-angularjs-ngcart-to-build-shopping-cart-for-ecommerce
