### ISSUE TITLE
addItem() does not behave properly when optionnal parameter quantity is not set

### ISSUE THREAD

**Issue by humbkr** [snapjay/ngCart#7]
When addItem() is called without a quantity set, the setQuantity() method set the value of this._quantity to 1 instead of adding 1 to the total quantity.

The problem is the line 267 of ngCart.js:
this._quantity = 1; should be this._quantity++;

I think this is an issue as quantity is an optionnal parameter.

**Comment by snapjay** [comment]
I don't understand this issue here?  - How can you increment a value if it hasn't been set yet.  If quantity is not set then it is defaulted to 1.

**Comment by snapjay** [comment]
Ah ok I see what you're saying - Lets continue this discussion in #11
