### ISSUE TITLE
Broken download on npm

### ISSUE THREAD

**Issue by kennynaoh** [snapjay/ngCart#71]
Hello @snapjay ,
I can't download the ngCart package on [npm](https://www.npmjs.com/package/ngCart) by this command ```npm install ngCart```.
Could you confirm this and fix it?
Thanks very much!

https://github.com/cdnjs/cdnjs/issues/7881

**Comment by PeterDaveHello** [comment]
@kennynaoh you say that you can't download, but you didn't provide any useful information even the log or error message, so how can people help you?

**Comment by PeterDaveHello** [comment]
BTW, I have no problem with using [ied](https://github.com/alexanderGugel/ied), for [pnpm](https://github.com/rstacruz/pnpm), it may need to install bower first.

**Comment by kennynaoh** [comment]
Thanks.
I can install it by using bower install.

**Comment by snapjay** [comment]
`npm install ngCart`
seems to work fine
