### ISSUE TITLE
Will ngCart be updated to 1.5?

### ISSUE THREAD

**Issue by finfort** [snapjay/ngCart#72]
Using component style... is it supported write now?

**Comment by snapjay** [comment]
I'm not actively updating ng-Cart. If a PR is submitted I can merge it

**Comment by finfort** [comment]
Can you help with [this](http://stackoverflow.com/questions/37614239/how-to-update-angular-1-2-service-to-1-5-in-angular-2-style), i am working on updating it to 1.5
