### ISSUE TITLE
[$rootScope:infdig] 10 $digest() iterations reached. Aborting!

### ISSUE THREAD

**Issue by brandhaug** [snapjay/ngCart#77]
Running a MEAN stack web application, and i'm trying to implement the ngCart. Whenever I add a directive from ngCart like <ngcart-addtocart> or <ngcart-summary> to the html I get the error: 

angular.js:68 Uncaught Error: [$rootScope:infdig] 10 $digest() iterations reached. Aborting!
Watchers fired in the last 5 iterations: [[{"msg":"fn: regularInterceptedExpression","newVal":3},{"msg":"fn: regularInterceptedExpression","newVal":".........

**Comment by pjstol** [comment]
Did you ever find the solution to this??, I'm having the same problem.
